"""empty message

Revision ID: 28a23e943f36
Revises: 43f4c3c83a58
Create Date: 2025-04-05 21:26:22.310643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28a23e943f36'
down_revision: Union[str, None] = '43f4c3c83a58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite_item', sa.Column('product_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'favorite_item', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favorite_item', type_='foreignkey')
    op.drop_column('favorite_item', 'product_id')
    # ### end Alembic commands ###
